import { createSupabaseServerClient } from "@/lib/supabase/server";

export type PublicEntity = { canonicalName: string; description: string | null; entityType: string; id: string; publicId: string; publishedAt: string | null; slug: string | null };
export type PublicSource = { canonicalUrl: string | null; id: string; publisher: string | null; sourceType: string; title: string };

function safeExternalUrl(value: string | null) { if (!value) return null; try { const url = new URL(value); return url.protocol === "http:" || url.protocol === "https:" ? url.toString() : null; } catch { return null; } }
function mapEntity(row: { canonical_name: string; description: string | null; entity_type: string; id: string; public_id: string; published_at: string | null; slug: string | null }): PublicEntity { return { canonicalName: row.canonical_name, description: row.description, entityType: row.entity_type, id: row.id, publicId: row.public_id, publishedAt: row.published_at, slug: row.slug }; }

export async function getPublicStats() { const supabase = await createSupabaseServerClient(); const [entities,cultivars,breeders,sources]=await Promise.all([supabase.from("entities").select("id",{count:"exact",head:true}),supabase.from("entities").select("id",{count:"exact",head:true}).eq("entity_type","cultivar"),supabase.from("entities").select("id",{count:"exact",head:true}).eq("entity_type","breeder"),supabase.from("sources").select("id",{count:"exact",head:true})]); const error=entities.error??cultivars.error??breeders.error??sources.error;if(error)throw error;return{entities:entities.count??0,cultivars:cultivars.count??0,breeders:breeders.count??0,sources:sources.count??0}; }
export async function getPublicEntities(entityType:"cultivar"|"breeder",limit=24){const supabase=await createSupabaseServerClient();const{data,error}=await supabase.from("entities").select("id, public_id, canonical_name, entity_type, slug, description, published_at").eq("entity_type",entityType).order("canonical_name").limit(limit);if(error)throw error;return data.map(mapEntity);}
export async function getPublicEntityBySlug(entityType:"cultivar"|"breeder",slug:string){const supabase=await createSupabaseServerClient();const{data,error}=await supabase.from("entities").select("id, public_id, canonical_name, entity_type, slug, description, published_at").eq("entity_type",entityType).eq("slug",slug).maybeSingle();if(error)throw error;return data?mapEntity(data):null;}

export async function getPublicCultivarResearch(slug:string){
 const supabase=await createSupabaseServerClient(); const entity=await getPublicEntityBySlug("cultivar",slug); if(!entity)return null;
 const [cultivar,names,claims,lineage,descendants]=await Promise.all([
  supabase.from("cultivars").select("origin_country_code, year_introduced").eq("id",entity.id).maybeSingle(),
  supabase.from("entity_names").select("id, name, name_type, status, source_document_id").eq("entity_id",entity.id).order("name"),
  supabase.from("claims").select("id, predicate, object_entity_id, object_text, object_number, object_date, object_boolean, status, confidence").eq("subject_entity_id",entity.id).neq("status","rejected").order("created_at"),
  supabase.from("lineage_relationships").select("id, parent_entity_id, parent_role, status, confidence").eq("child_entity_id",entity.id).neq("status","rejected"),
  supabase.from("lineage_relationships").select("id, child_entity_id, parent_role, status, confidence").eq("parent_entity_id",entity.id).neq("status","rejected")
 ]); const error=cultivar.error??names.error??claims.error??lineage.error??descendants.error;if(error)throw error;
 const relatedIds=[...new Set([...claims.data.flatMap(c=>c.object_entity_id?[c.object_entity_id]:[]),...lineage.data.map(r=>r.parent_entity_id),...descendants.data.map(r=>r.child_entity_id)])];
 const related=relatedIds.length?await supabase.from("entities").select("id, public_id, canonical_name, entity_type, slug, description, published_at").in("id",relatedIds):{data:[],error:null}; if(related.error)throw related.error; const entityMap=new Map(related.data.map(row=>[row.id,mapEntity(row)]));
 const claimIds=claims.data.map(c=>c.id), lineageIds=lineage.data.map(r=>r.id);
 const [claimEvidence,lineageEvidence]=await Promise.all([
  claimIds.length?supabase.from("claim_evidence").select("claim_id, source_document_id, stance, locator").in("claim_id",claimIds):Promise.resolve({data:[],error:null}),
  lineageIds.length?supabase.from("lineage_evidence").select("lineage_relationship_id, source_document_id, stance, locator").in("lineage_relationship_id",lineageIds):Promise.resolve({data:[],error:null})
 ]); if(claimEvidence.error)throw claimEvidence.error;if(lineageEvidence.error)throw lineageEvidence.error;
 const documentIds=[...new Set([...names.data.flatMap(n=>n.source_document_id?[n.source_document_id]:[]),...claimEvidence.data.map(e=>e.source_document_id),...lineageEvidence.data.map(e=>e.source_document_id)])];
 const documents=documentIds.length?await supabase.from("source_documents").select("id, source_id, title, document_url, published_at, retrieved_at, relationship_type").in("id",documentIds):{data:[],error:null};if(documents.error)throw documents.error;
 const sourceIds=[...new Set(documents.data.map(d=>d.source_id))]; const sources=sourceIds.length?await supabase.from("sources").select("id, title, publisher, source_type, canonical_url").in("id",sourceIds):{data:[],error:null};if(sources.error)throw sources.error;
 const sourceMap=new Map(sources.data.map(s=>[s.id,{id:s.id,title:s.title,publisher:s.publisher,sourceType:s.source_type,canonicalUrl:safeExternalUrl(s.canonical_url)}]));
 const documentMap=new Map(documents.data.map(d=>[d.id,{...d,document_url:safeExternalUrl(d.document_url),source:sourceMap.get(d.source_id)??null}]));
 const withEvidence=(id:string,kind:"claim"|"lineage")=>(kind==="claim"?claimEvidence.data.filter(e=>e.claim_id===id):lineageEvidence.data.filter(e=>e.lineage_relationship_id===id)).map(e=>({...e,document:documentMap.get(e.source_document_id)??null}));
 return {entity,cultivar:cultivar.data,names:names.data.map(n=>({...n,document:n.source_document_id?documentMap.get(n.source_document_id)??null:null})),claims:claims.data.map(c=>({...c,objectEntity:c.object_entity_id?entityMap.get(c.object_entity_id)??null:null,evidence:withEvidence(c.id,"claim")})),lineage:lineage.data.map(r=>({...r,parent:entityMap.get(r.parent_entity_id)??null,evidence:withEvidence(r.id,"lineage")})),descendants:descendants.data.map(r=>({...r,child:entityMap.get(r.child_entity_id)??null})),sources:[...sourceMap.values()]};
}

export async function searchPublicEntities(rawQuery:string,limit=40){const query=rawQuery.trim().slice(0,100);if(query.length<2)return[];const supabase=await createSupabaseServerClient();const pattern=`%${query.replaceAll("%","\\%").replaceAll("_","\\_")}%`;const[canonicalMatches,publicIdMatches]=await Promise.all([supabase.from("entities").select("id, public_id, canonical_name, entity_type, slug, description, published_at").ilike("canonical_name",pattern).limit(limit),supabase.from("entities").select("id, public_id, canonical_name, entity_type, slug, description, published_at").ilike("public_id",pattern).limit(limit)]);const{nameMatches,error:nameError}=await (async()=>{const r=await supabase.from("entity_names").select("entity_id").ilike("normalized_name",pattern).limit(limit);return{nameMatches:r.data,error:r.error};})();if(canonicalMatches.error)throw canonicalMatches.error;if(publicIdMatches.error)throw publicIdMatches.error;if(nameError)throw nameError;const directMatches=[...canonicalMatches.data];const directIds=new Set(directMatches.map(e=>e.id));for(const e of publicIdMatches.data)if(!directIds.has(e.id)){directIds.add(e.id);directMatches.push(e);}const aliasIds=[...new Set(nameMatches.map(n=>n.entity_id))].filter(id=>!directIds.has(id));let aliasMatches:typeof directMatches=[];if(aliasIds.length){const{data,error}=await supabase.from("entities").select("id, public_id, canonical_name, entity_type, slug, description, published_at").in("id",aliasIds).limit(Math.max(0,limit-directMatches.length));if(error)throw error;aliasMatches=data;}return[...directMatches,...aliasMatches].slice(0,limit).map(mapEntity);}
export async function getPublicSource(id:string){if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(id))return null;const supabase=await createSupabaseServerClient();const{data,error}=await supabase.from("sources").select("id, title, publisher, source_type, canonical_url").eq("id",id).maybeSingle();if(error)throw error;if(!data)return null;const{data:documents,error:documentsError}=await supabase.from("source_documents").select("id, title, document_url, published_at, retrieved_at, relationship_type").eq("source_id",id).order("published_at",{ascending:false,nullsFirst:false});if(documentsError)throw documentsError;return{source:{canonicalUrl:safeExternalUrl(data.canonical_url),id:data.id,publisher:data.publisher,sourceType:data.source_type,title:data.title} satisfies PublicSource,documents:documents.map(d=>({...d,document_url:safeExternalUrl(d.document_url)}))};}