"use client";

import { useCallback, useMemo, useState } from "react";
import { Background, Controls, MarkerType, ReactFlow, type Edge, type Node } from "@xyflow/react";
import "@xyflow/react/dist/style.css";

type GraphEntity={id:string;publicId:string;canonicalName:string;slug:string|null;entityType:string};
type GraphEdge={id:string;childEntityId:string;parentEntityId:string;parentRole:string;status:string;confidence:number|null};
type Neighborhood={focus:GraphEntity;nodes:GraphEntity[];edges:GraphEdge[];truncated:boolean};

const label=(v:string)=>v.replaceAll("_"," ");
function position(nodes:GraphEntity[],edges:GraphEdge[],focusId:string):Node[]{const parents=new Set(edges.filter(e=>e.childEntityId===focusId).map(e=>e.parentEntityId));const children=new Set(edges.filter(e=>e.parentEntityId===focusId).map(e=>e.childEntityId));let pi=0,ci=0,oi=0;return nodes.map(n=>{let x=0,y=180;if(n.id===focusId){x=260;y=180}else if(parents.has(n.id)){x=pi++*240;y=20}else if(children.has(n.id)){x=ci++*240;y=340}else{x=oi++*240;y=520}return{id:n.id,position:{x,y},data:{label:n.canonicalName},style:{width:190,borderRadius:12,border:"1px solid var(--line-strong)",background:"var(--surface)",color:"var(--foreground)",padding:12,fontSize:13,fontWeight:n.id===focusId?700:500}}})}
function flowEdges(edges:GraphEdge[]):Edge[]{return edges.map(e=>({id:e.id,source:e.parentEntityId,target:e.childEntityId,label:`${label(e.parentRole)} · ${label(e.status)}`,markerEnd:{type:MarkerType.ArrowClosed},animated:e.status==="disputed",style:{strokeDasharray:e.status==="candidate"?"6 4":undefined},labelStyle:{fontSize:10}}))}

export function LineageExplorer({initial}:{initial:Neighborhood}){const[graph,setGraph]=useState(initial);const[busy,setBusy]=useState<string|null>(null);const[error,setError]=useState<string|null>(null);const nodes=useMemo(()=>position(graph.nodes,graph.edges,initial.focus.id),[graph,initial.focus.id]);const edges=useMemo(()=>flowEdges(graph.edges),[graph.edges]);
const expand=useCallback(async(id:string)=>{setBusy(id);setError(null);try{const r=await fetch(`/api/lineage/${id}?direction=both&limit=12`);if(!r.ok)throw new Error("Expansion could not be loaded.");const next:Neighborhood=await r.json();setGraph(current=>({focus:current.focus,nodes:[...new Map([...current.nodes,...next.nodes].map(n=>[n.id,n])).values()],edges:[...new Map([...current.edges,...next.edges].map(e=>[e.id,e])).values()],truncated:current.truncated||next.truncated}))}catch(e){setError(e instanceof Error?e.message:"Expansion could not be loaded.")}finally{setBusy(null)}},[]);
return <div className="space-y-4"><div className="h-[32rem] overflow-hidden rounded-2xl border border-[var(--line)] bg-[var(--surface)]" aria-label="Interactive cultivar lineage graph"><ReactFlow nodes={nodes} edges={edges} fitView minZoom={0.25} maxZoom={1.8} nodesDraggable={false} nodesConnectable={false} elementsSelectable><Background gap={24}/><Controls showInteractive={false}/></ReactFlow></div><div className="flex flex-wrap gap-2">{graph.nodes.map(n=><button key={n.id} type="button" disabled={busy!==null} onClick={()=>expand(n.id)} className="rounded-full border border-[var(--line-strong)] px-3 py-2 text-xs disabled:opacity-50">{busy===n.id?"Loading…":`Expand ${n.canonicalName}`}</button>)}</div>{graph.truncated&&<p className="text-xs text-[var(--muted)]">This view is intentionally bounded. Expand a cultivar to load another small neighborhood.</p>}{error&&<p role="alert" className="text-sm text-[var(--muted)]">{error}</p>}<details className="rounded-xl border border-[var(--line)] p-5"><summary className="cursor-pointer font-semibold">Accessible lineage list</summary><ul className="mt-4 space-y-3">{graph.edges.map(e=>{const parent=graph.nodes.find(n=>n.id===e.parentEntityId);const child=graph.nodes.find(n=>n.id===e.childEntityId);return <li key={e.id} className="text-sm"><strong>{parent?.canonicalName??"Unknown parent"}</strong> → {child?.canonicalName??"Unknown child"} <span className="text-[var(--muted)]">({label(e.parentRole)}, {label(e.status)})</span></li>})}</ul></details></div>}
